name: 'clang-format Code Formatter'
description: 'Runs clang-format on your source code so your users do not have to'
author: 'abelREK'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
